### ISSUE TITLE
Attribute error

### ISSUE THREAD

**Issue by Tortoise17** [OdysseasKr/music-som#2]
Dear Friend. 

There is one error in creation of the .h5 file. 

Traceback (most recent call last):
  File "createh5.py", line 80, in <module>
    create_dataset(sys.argv[1], sys.argv[2])
  File "createh5.py", line 69, in create_dataset
    out_file.create_dataset(label, data=data_matrix[(data_labels == label).flatten()])
AttributeError: 'bool' object has no attribute 'flatten'

Can you help. why is it so?

Greetings. 

Khawar

**Comment by OdysseasKr** [comment]
Hello, thank you for pointing out the issue. I have just fixed this in db33ecd157d0f0c334767918d0773b45b5ccf805 and it should be fine now.
